[[main]]
none = "none"

[[main]]
name = "Projects"
pageRef = "/projects"
identifier = "UdhC8DEt3n"
weight = 99

[[main]]
name = "Writeups"
pageRef = "/writeups"
identifier = "HR29r5eigU"
weight = 999

[[main]]
name = "Resume"
url = "/resume.pdf"
identifier = "wR7BPUz6BD"
weight = 9999

[[footer]]
none = "none"
